### PR TITLE
Added the About us and Contact us page

### PR DESCRIPTION
**Pull request by Deepankar1484**
Hey @widewipe, 
As told I have build a about us and Contact us Page with a responsive design .
In addition to that i have build a Footer for the same.
About us page
Screenshot 2024-10-16 at 11 36 40 AM
Footer
Screenshot 2024-10-16 at 11 36 54 AM
Contact us page
Screenshot 2024-10-16 at 6 05 18 PM

### CODE REVIEW

**Comment by aether-flux** [comment]
Can you change the contact page's button to the yellow-orange color #FFBE7A or something around this color? As that'll be the main color of the website. 

Other than that, everything looks nice. Good work 👍

**Comment by Deepankar1484** [comment]
Yes sure, I will change the color in an hour.

**Comment by Deepankar1484** [comment]
Sorry for the delay, Got busy with the other stuff. 
@widewipe Please Check the work and Merge it.

**Comment by aether-flux** [comment]
Nice work. It looks great.

**Comment by Deepankar1484** [comment]
Thanks Man, As told Finished the work in 24 hours of assigning the task.
Greatfull of you to let me contribute to this amazing website. 
Thanks,
Deepankar Garg

**Pull request merged**
